---

- name: download latest chunter
  get_url: url=http://release.project-fifo.net/chunter/{{chunter_release}}/{{chunter_download_name}} dest=/opt/chunter-latest.gz

- name: unpack chunter
  shell: gunzip -f /opt/chunter-latest.gz

- name: install chunter
  shell: sh /opt/chunter-latest -f
  notify: Bounce Chunter